"""
boss_orchestrator.py — Boss Orchestrator for chaining sequential tools.
Decomposes user instruction into JSON tool calls and dispatches them in sequence.
"""

import asyncio
import json
from google.genai import types
from actions.prime_utils import UnifiedModelClient

def boss_orchestrator(parameters: dict, player=None) -> str:
    """
    Boss Orchestrator: Chains sequential tool calls based on a high-level command.
    """
    command = parameters.get("command", "")
    if not command:
        return "Please provide 'command' parameter, sir."

    def log(msg: str):
        print(f"[Boss] {msg}")
        if player:
            player.write_log(f"[Boss] {msg}")

    client = UnifiedModelClient()

    log(f"Received boss instruction: \"{command}\"")
    
    # Decompose command using Gemini
    system_instruction = (
        "You are Varon-AI, the unified Boss Orchestrator. "
        "Decompose the high-level user command into a clean, sequential list of JSON tool calls. "
        "Available tool names: 'web_search', 'web_scraper', 'write_to_file', 'image_generator', 'autonomy_engine', 'macro_automation'.\n"
        "Return ONLY a JSON object of format:\n"
        "{\n"
        "  \"steps\": [\n"
        "    {\"tool\": \"tool_name\", \"args\": {\"arg_name\": \"value\"}}\n"
        "  ]\n"
        "}"
    )
    
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=command,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                response_mime_type="application/json"
            )
        )
        
        pipeline = json.loads(response.text.strip())
        steps = pipeline.get("steps", [])
        if not steps:
            return "No orchestration steps generated by Varon-AI, sir."
            
        log(f"Generated plan: {len(steps)} steps.")
        accumulated_results = []
        
        # We need to execute each step sequentially.
        from core.tool_dispatcher import dispatch_tool
        
        # Simple helper to run async function synchronously or inside running loop
        def run_async(coro):
            try:
                loop = asyncio.get_event_loop()
            except RuntimeError:
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
            
            if loop.is_running():
                # If running inside a server or PyQt loop, run via run_coroutine_threadsafe
                import threading
                fut = asyncio.run_coroutine_threadsafe(coro, loop)
                return fut.result()
            else:
                return loop.run_until_complete(coro)

        for idx, step in enumerate(steps):
            tool_name = step.get("tool")
            args = step.get("args", {})
            log(f"Executing Step #{idx+1}: {tool_name} with args {args}")
            
            async def run_step():
                loop = asyncio.get_running_loop()
                # Dummy speak lambda
                speak_lambda = lambda t: print(f"[Boss speak] {t}")
                return await dispatch_tool(tool_name, args, player, speak_lambda, loop)
                
            res = run_async(run_step())
            log(f"Step #{idx+1} result: {str(res)[:100]}...")
            accumulated_results.append(f"### Step #{idx+1} ({tool_name})\n{res}\n")
            
        return "\n".join(accumulated_results)
        
    except Exception as e:
        return f"Boss orchestration failed: {e}"
