# actions/document_generator.py
# Voice-driven professional document & PDF generator.
# Generates styled PDFs (via reportlab) or Markdown fallback to Desktop/Downloads.

import json
import os
import sys
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent.parent
CONFIG_PATH = BASE_DIR / "config" / "api_keys.json"

# ─── Output Path Helpers ──────────────────────────────────────────────────────

def _resolve_output_dir(destination: str) -> Path:
    """Map shorthand destination strings to real paths."""
    shortcuts = {
        "desktop":   Path.home() / "Desktop",
        "downloads": Path.home() / "Downloads",
        "sat output": Path.home() / "Downloads" / "sat output",
        "documents": Path.home() / "Documents",
    }
    key = destination.lower().strip()
    if key in shortcuts:
        return shortcuts[key]
    p = Path(destination).expanduser()
    return p


# ─── PDF Generation ──────────────────────────────────────────────────────────

def _generate_pdf(title: str, content: str, author: str, output_path: Path) -> str:
    """Generate a styled PDF using reportlab if available."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.platypus import Table, TableStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=2.5 * cm,
            leftMargin=2.5 * cm,
            topMargin=2.5 * cm,
            bottomMargin=2.5 * cm,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "SaturdayTitle",
            parent=styles["Title"],
            fontSize=22,
            textColor=colors.HexColor("#1a1a2e"),
            spaceAfter=6,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
        )
        subtitle_style = ParagraphStyle(
            "SaturdaySubtitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#555577"),
            spaceAfter=18,
            alignment=TA_CENTER,
        )
        body_style = ParagraphStyle(
            "SaturdayBody",
            parent=styles["BodyText"],
            fontSize=11,
            leading=16,
            textColor=colors.HexColor("#1a1a1a"),
            alignment=TA_JUSTIFY,
            spaceAfter=10,
        )
        heading_style = ParagraphStyle(
            "SaturdayHeading",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#16213e"),
            spaceAfter=8,
            spaceBefore=14,
            fontName="Helvetica-Bold",
        )

        story = []

        # Title block
        story.append(Paragraph(title, title_style))
        meta = f"Generated by S.A.T.U.R.D.A.Y — {datetime.now().strftime('%B %d, %Y at %H:%M')}"
        if author:
            meta = f"Author: {author} &nbsp;|&nbsp; " + meta
        story.append(Paragraph(meta, subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#4a90d9"), spaceAfter=16))

        # Parse content into sections — split on lines starting with ## or #
        paragraphs = content.split("\n")
        for para in paragraphs:
            stripped = para.strip()
            if not stripped:
                story.append(Spacer(1, 6))
                continue
            if stripped.startswith("## "):
                story.append(Paragraph(stripped[3:], heading_style))
            elif stripped.startswith("# "):
                story.append(Paragraph(stripped[2:], heading_style))
            elif stripped.startswith("- ") or stripped.startswith("• "):
                # Bullet list item
                bullet_style = ParagraphStyle(
                    "Bullet", parent=body_style,
                    leftIndent=20, bulletIndent=8,
                    spaceBefore=2, spaceAfter=2
                )
                story.append(Paragraph(f"• {stripped[2:]}", bullet_style))
            else:
                story.append(Paragraph(stripped, body_style))

        # Footer spacer
        story.append(Spacer(1, 18))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
        footer_style = ParagraphStyle(
            "Footer", parent=styles["Normal"],
            fontSize=8, textColor=colors.gray,
            alignment=TA_CENTER, spaceBefore=6
        )
        story.append(Paragraph("S.A.T.U.R.D.A.Y Assistant — IP Verse © Pratik Thorat", footer_style))

        doc.build(story)
        return f"PDF document '{output_path.name}' saved to {output_path.parent}, sir."
    except ImportError:
        return None  # Signal to fall back to Markdown


def _generate_markdown(title: str, content: str, author: str, output_path: Path) -> str:
    """Generate a clean Markdown document as fallback."""
    now = datetime.now().strftime("%B %d, %Y at %H:%M")
    header = f"# {title}\n\n"
    if author:
        header += f"**Author:** {author}  \n"
    header += f"**Generated:** {now} by S.A.T.U.R.D.A.Y  \n\n---\n\n"
    full = header + content + "\n\n---\n*S.A.T.U.R.D.A.Y Assistant — IP Verse © Pratik Thorat*\n"
    output_path.write_text(full, encoding="utf-8")
    return f"Document '{output_path.name}' saved to {output_path.parent}, sir."


def _generate_txt(title: str, content: str, author: str, output_path: Path) -> str:
    """Generate a plain text document."""
    now = datetime.now().strftime("%B %d, %Y at %H:%M")
    header = f"{title}\n{'='*len(title)}\n"
    if author:
        header += f"Author: {author}\n"
    header += f"Generated: {now} by S.A.T.U.R.D.A.Y\n\n"
    full = header + content + "\n\n— S.A.T.U.R.D.A.Y Assistant — IP Verse © Pratik Thorat —\n"
    output_path.write_text(full, encoding="utf-8")
    return f"Text document '{output_path.name}' saved to {output_path.parent}, sir."


# ─── Summary Generator ────────────────────────────────────────────────────────

def _auto_format_sections(content: str, sections: list[dict]) -> str:
    """If sections are provided, format them as structured content."""
    if not sections:
        return content
    lines = []
    if content:
        lines.append(content)
        lines.append("")
    for sec in sections:
        heading = sec.get("heading", "")
        body = sec.get("body", "")
        if heading:
            lines.append(f"## {heading}")
        if body:
            lines.append(body)
        lines.append("")
    return "\n".join(lines)


# ─── Main Dispatcher ──────────────────────────────────────────────────────────

def document_generator(parameters: dict, player=None, speak=None) -> str:
    """
    Professional document and PDF generator tool for Saturday.
    Creates styled PDF (via reportlab), Markdown, or TXT documents.

    Supported formats: pdf | markdown | txt
    Supported destinations: desktop | downloads | sat output | documents | <custom path>
    """
    title = parameters.get("title", f"Saturday Document — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    content = parameters.get("content", "").strip()
    sections = parameters.get("sections", [])
    author = parameters.get("author", "Pratik Thorat")
    fmt = parameters.get("format", "pdf").lower().strip()
    destination = parameters.get("destination", "desktop").strip()
    filename = parameters.get("filename", "").strip()

    # Build content from sections if provided
    full_content = _auto_format_sections(content, sections)

    if not full_content:
        result = "Please provide 'content' or 'sections' to generate a document, sir."
        if speak:
            speak(result)
        return result

    # Determine output directory and file name
    output_dir = _resolve_output_dir(destination)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build file name
    safe_title = "".join(c if c.isalnum() or c in "_ -" else "_" for c in title)[:50].strip()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    if not filename:
        filename = f"{safe_title}_{timestamp}"

    # Generate based on requested format
    if fmt == "pdf":
        output_path = output_dir / f"{filename}.pdf"
        result = _generate_pdf(title, full_content, author, output_path)
        if result is None:
            # reportlab not installed — fall back to Markdown
            output_path = output_dir / f"{filename}.md"
            result = _generate_markdown(title, full_content, author, output_path)
            result = "[Note: reportlab not installed — saved as Markdown instead.] " + result

    elif fmt == "markdown" or fmt == "md":
        output_path = output_dir / f"{filename}.md"
        result = _generate_markdown(title, full_content, author, output_path)

    else:  # txt
        output_path = output_dir / f"{filename}.txt"
        result = _generate_txt(title, full_content, author, output_path)

    if player:
        player.write_log(f"SATURDAY (DocGen): {result}")
    if speak:
        speak(result[:180])
    return result
