"""
local_llm.py — Integrates local Ollama models to provide robust offline intelligence support.

Allows IP Prime to fall back to running a local llama3 model when connection limits or
offline environment parameters are encountered.
"""

from __future__ import annotations

import logging
import os
import requests
from typing import Any, Optional

logger = logging.getLogger("ip_prime.local_llm")

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
DEFAULT_OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3")

def switch_to_offline_mode(player: Optional[Any] = None) -> str:
    """Sets the environment flag to enforce local LLM offline execution."""
    os.environ["OFFLINE_MODE"] = "true"
    msg = "Offline Mode activated, sir! IP Prime will now run all intelligence tasks via local Ollama."
    if player and hasattr(player, "write_log"):
        player.write_log(f"SYS: {msg}")
    logger.info("Switched to offline mode.")
    return msg

def switch_to_online_mode(player: Optional[Any] = None) -> str:
    """Clears the environment flag to resume standard online Gemini operations."""
    os.environ["OFFLINE_MODE"] = "false"
    msg = "Online Mode resumed, sir! Standard cloud-first Gemini channels are active once again."
    if player and hasattr(player, "write_log"):
        player.write_log(f"SYS: {msg}")
    logger.info("Switched to online mode.")
    return msg

def is_offline_mode_active() -> bool:
    """Returns True if the offline override variable is flagged."""
    return os.environ.get("OFFLINE_MODE", "false").lower() == "true"

def generate_local_response(prompt: str, system_instruction: Optional[str] = None) -> str:
    """
    Sends a generation query directly to local Ollama API.

    Args:
        prompt: The user query string.
        system_instruction: The configured personality rules.

    Returns:
        Structured text outcome generated by the local LLM.
    """
    try:
        url = f"{OLLAMA_HOST}/api/generate"
        payload = {
            "model": DEFAULT_OLLAMA_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": 0.7
            }
        }
        if system_instruction:
            payload["system"] = system_instruction

        logger.info("Querying local Ollama model %s...", DEFAULT_OLLAMA_MODEL)
        response = requests.post(url, json=payload, timeout=15)
        if response.status_code == 200:
            return response.json().get("response", "").strip()
        else:
            return (
                f"Ollama local API standard status error: {response.status_code}. "
                "Aapki local model service responsive nahi hai, sir."
            )
    except requests.exceptions.RequestException as re:
        logger.error("Failed to connect to local Ollama: %s", re)
        return (
            "Local Ollama connection failed, sir! Please verify that Ollama is "
            "started and listening on port 11434. Run 'ollama run llama3' in your terminal."
        )
    except Exception as e:
        logger.error("Error in local LLM generation: %s", e)
        return f"Local LLM exception error: {e}"

def local_llm(parameters: dict[str, Any], player: Optional[Any] = None) -> str:
    """Main dispatcher for local_llm action."""
    action = parameters.get("action", "").lower().strip()
    if action == "switch_offline":
        return switch_to_offline_mode(player)
    elif action == "switch_online":
        return switch_to_online_mode(player)
    elif action == "status":
        state = "OFFLINE" if is_offline_mode_active() else "ONLINE"
        return f"Currently running in {state} mode, sir. Active model is local: {DEFAULT_OLLAMA_MODEL}."
    else:
        return "Unknown local LLM operation parameter, sir."
